# a compose file to facilitate local config generation suitable for templating
version: '3'
services:
  homeassistant_configbuild:
    build: ./app
    ports:
    - "8123:8123"
    volumes:
    - ./secrets/secrets.yaml:/.secrets/secrets.yaml:ro
    - ./secrets/service_account.json:/.secrets/service_account.json:ro
    - ./app/config:/config:rw
