ingress:
  class: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: home-assistant-32c1fc.mooo.com
      paths:
        - path: /
  tls:
    - hosts:
      - home-assistant-32c1fc.mooo.com
      secretName: home-assistant-cert
