- id: winter_morning_on
  alias: winter | morning on
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition: []
  action:
  - service: climate.turn_on
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_temperature
    data:
      temperature: 20
      hvac_mode: heat
    target:
      entity_id: climate.home_ac_unit
  mode: single
- id: winter_morning_off
  alias: winter | morning off
  description: ''
  trigger:
  - platform: time
    at: 08:30
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.home_ac_unit
  mode: single
- id: winter_evening_on
  alias: winter | evening on
  description: ''
  trigger:
  - platform: time
    at: '16:30'
  condition: []
  action:
  - service: climate.turn_on
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_temperature
    data:
      temperature: 20
      hvac_mode: heat
    target:
      entity_id: climate.home_ac_unit
  mode: single
- id: winter_evening_off
  alias: winter | evening off
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.home_ac_unit
  mode: single
