- id: winter_morning_on
  alias: winter | morning on
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: climate.home_ac_unit
      below: '16'
    - condition: numeric_state
      entity_id: sensor.moss_vale_temp_feels_like
      below: '16'
  action:
  - service: climate.turn_on
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_temperature
    data:
      temperature: 20
      hvac_mode: heat
    target:
      entity_id: climate.home_ac_unit
  mode: single
- id: winter_morning_off
  alias: winter | morning off
  description: ''
  trigger:
  - platform: time
    at: 08:30
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.home_ac_unit
  mode: single
- id: winter_evening_on
  alias: winter | evening on
  description: ''
  trigger:
  - platform: time
    at: '16:30'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: climate.home_ac_unit
      below: '16'
    - condition: numeric_state
      entity_id: sensor.moss_vale_temp_feels_like
      below: '16'
  action:
  - service: climate.turn_on
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      entity_id: climate.home_ac_unit
  - service: climate.set_temperature
    data:
      temperature: 20
      hvac_mode: heat
    target:
      entity_id: climate.home_ac_unit
  mode: single
- id: winter_evening_off
  alias: winter | evening off
  description: ''
  trigger:
  - platform: time
    at:
      - '22:00:00'
      - '22:30:00'
      - '23:00:00'
      - '23:30:00'
      - '01:00:00'
      - '02:00:00'
      - '03:00:00'
      - '04:00:00'
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.home_ac_unit
  mode: single
