# https://github.com/ministryofjustice/analytics-platform-helm-charts/tree/main/charts/cert-manager-resources
repositories:
- name: cert-manager
  url: https://charts.jetstack.io
releases:
- name: cert-manager
  namespace: cert-manager
  createNamespace: true
  version: v1.4.0
  chart: jetstack/cert-manager
  values:
  - installCRDs: true
