releases:
- name: letsencrypt
  namespace: cert-manager
  createNamespace: true
  chart: ../../helm/charts/cert-manager-issuer
  values:
  - issuer:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
  - ../../secrets/issuer.yaml